### PR TITLE
adding support for laravel 11

### PR DESCRIPTION
**Pull request by atmonshi**
this pr is updating the composer `laravel/framework` version constraint to support v11

### CODE REVIEW

**Comment by danharrin** [comment]
@AnourValar Laravel 11 is available if you explicitly require it, hence why this PR can be merged at any time

**Comment by AnourValar** [comment]
I need to update some tests to ensure that the package works with Laravel 11 properly.

**Comment by danharrin** [comment]
Thanks. Setting up a GitHub actions CI for this would allow people to perform these tests for you

**Comment by mokhosh** [comment]
> I need to update some tests to ensure that the package works with Laravel 11 properly.

@AnourValar i can help if you have something specific in mind

**Comment by AnourValar** [comment]
Laravel 11 support added

**Pull request closed without merging**
